import {
  Car,
  Building2,
  Shirt,
  Archive,
  Monitor,
  Film,
  Users,
  Gift,
  Leaf,
  Paintbrush,
  Sofa,
  Hammer,
  Home,
  Music,
  FileText,
  PawPrint,
  Dumbbell,
  Puzzle,
} from "lucide-react";

export const CATEGORIES = [
  { name: "Vehicles", icon: Car },
  { name: "Property Rentals", icon: Building2 },
  { name: "Apparel", icon: Shirt },
  { name: "Classifieds", icon: Archive },
  { name: "Electronics", icon: Monitor },
  { name: "Entertainment", icon: Film },
  { name: "Family", icon: Users },
  { name: "Free Stuff", icon: Gift },
  { name: "Garden & Outdoor", icon: Leaf },
  { name: "Hobbies", icon: Paintbrush },
  { name: "Home Goods", icon: Sofa },
  { name: "Home Improvement", icon: Hammer },
  { name: "Home Sales", icon: Home },
  { name: "Musical Instruments", icon: Music },
  { name: "Office Supplies", icon: FileText },
  { name: "Pet Supplies", icon: PawPrint },
  { name: "Sporting Goods", icon: Dumbbell },
  { name: "Toys & Games", icon: Puzzle },
];
